
GET http://localhost:3000

###
 
GET http://localhost:3000/ads


### Ads filtered for Bordeaux

GET http://localhost:3000/ads?location=Bordeaux


### Ads filtered for Montreuil sous bois

GET http://localhost:3000/ads/average?location=Montreuil sous bois


### Create an ad with a category
    
POST http://localhost:3000/ads
Content-Type: application/json
 
{
    "title": "2 Gourde",
    "description": "Grande contenance",
    "owner": "onsenfiche@gmail.com",
    "price": 9,
    "location": "Bordeaux",
    "createdAt": "2024-05-29T17:14:15.922Z",
    "category": {
        "name": "autre2"
    }
}

### get ads for categories

POST http://localhost:3000/ads/forCategory
Content-Type: application/json

{
    "categoryNames": ["vêtement", "autre"]
}

### forCategoryStartingByV

POST http://localhost:3000/ads/forCategoryStartingByV
Content-Type: application/json

{
}

### get average ads price for autre

GET http://localhost:3000/ads/averageForAutre

###

POST http://localhost:3000/dump
Content-Type: text/plain

boug

### Delete ad by id

DELETE http://localhost:3000/ads
Content-Type: application/json

{
"id": 18
}

### Delete ad by minPrice

DELETE http://localhost:3000/ads
Content-Type: application/json

{
"minPrice": 40
}

### Update ad by id

PUT http://localhost:3000/ads
Content-Type: application/json
 
{
"id": 3,
"title": "Supreme rollerblade",
"description": "hey",
"owner": "roll.er@gmail.com",
"price": 10000.67,
"picture": "https://www.automobile-magazine.fr/asset/cms/34973/config/28294/apres-plusieurs-prototypes-la-bollore-bluecar-a-fini-par-devoiler-sa-version-definitive.jpg",
"location": "Mulhouse",
"createdAt": "2024-05-05T10:14:15.922Z"
}


