
GET http://localhost:3000

###

GET http://localhost:3000/ads


###

POST http://localhost:3000/ads
Content-Type: application/json

{
    "id": 3,
    "title": "Rollers",
    "description": "They are super",
    "owner": "roller.seller@gmail.com",
    "price": 10,
    "picture": "https://www.automobile-magazine.fr/asset/cms/34973/config/28294/apres-plusieurs-prototypes-la-bollore-bluecar-a-fini-par-devoiler-sa-version-definitive.jpg",
    "location": "Montreuil",
    "createdAt": "2024-05-28T10:14:15.922Z"
}

###

POST http://localhost:3000/dump
Content-Type: text/plain

boug