name: back_unit_tests

on: push

jobs:
  back_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TGC code
        uses: actions/checkout@v4
      - name: npm install dependencies
        run: cd backend && npm i
      - name: Move in back and Typescript transpile
        run: cd backend && npx tsc