name: back_unit_tests

on: 
  pull_request:
    branches: [ main, master ]

jobs:
  back-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Run tests
        run: cd backend && npm ci && npm run test